### ISSUE TITLE
Error: Cannot find module 'babel-core/register'

### ISSUE THREAD

**Issue by eanfs** [catalinmiron/react-native-dribbble-app#25]
Got error when start

module.js:339
    throw err;
    ^

Error: Cannot find module 'babel-core/register'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at module.exports (/Users/lirichen/Work/GithubRepo/react-native-dribbble-app/node_modules/react-native/packager/babelRegisterOnly.js:15:3)
    at Object.<anonymous> (/Users/lirichen/Work/GithubRepo/react-native-dribbble-app/node_modules/react-native/local-cli/cli.js:11:41)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
Process terminated. Press <enter> to close the window

**Comment by abhinav-singi** [comment]
clean npm install?

**Comment by catalinmiron** [comment]
@abhinav-singi can you please remind me in one week or so to update the whole project? Thanks!
